name: sassari
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.12.2
  - libxml2=2.10.3
  - lxml=4.9.2
  - matplotlib-inline=0.1.6
  - pandas=1.5.3
  - pip=23.0.1
  - python=3.9.16
  - spacy=3.5.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.1
  - spacy-model-en_core_web_md=3.5.0
  - spacy-model-fr_core_news_lg=3.5.0
  - spacy-model-fr_core_news_md=3.5.0
  - spacy-model-fr_core_news_sm=3.5.0
  - pip:
    - lyricsgenius==3.0.1
    - spacyfishing==0.1.8
    - matplotlib==3.7.1